base_url = "https://ewpratten.com"
title = "Evan Pratten"
description = "Evan Pratten is a college student, amateur radio operator, software developer, and more. This is his website."
default_language = "en"
compile_sass = true
build_search_index = true
generate_feed = true
feed_filename = "rss.xml"
minify_html = false

[markdown]
highlight_code = true
render_emoji = true
external_links_target_blank = true

[link_checker]
skip_prefixes = []
skip_anchor_prefixes = []
internal_level = "error"
external_level = "error"

[extra]
# Website
domain_name = "ewpratten.com"
# Me
name = "Evan Pratten"
profession = "Software Developer"
profile_photo = "https://branding.ewpratten.com/pfp/2022/460x460.png"
# Accounts
email = "evan@ewpratten.com"
github = "ewpratten"
linkedin = "ewpratten"
