base_url = "https://ewpratten.com"
title = "Evan Pratten"
description = "Evan Pratten is a college student, amateur radio operator, software developer, and more. This is his website."
default_language = "en"
compile_sass = true
build_search_index = true
generate_feed = true
feed_filename = "rss.xml"
minify_html = false

[markdown]
highlight_code = true
render_emoji = true
external_links_target_blank = true

[extra]
name = "Evan Pratten"
profession = "Software Developer"
email = "contact@ewpratten.com"
twitter = "ewpratten"
github = "ewpratten"
qrz = "va3zza"
linkedin = "ewpratten"
profile_photo = "https://avatars.githubusercontent.com/u/21065412"