base_url = "https://ewpratten.com"
title = "Evan Pratten"
description = "Evan Pratten is a software developer, amateur radio operator, and more. This is his website."
default_language = "en"
compile_sass = true
build_search_index = true
generate_feed = true
feed_filename = "rss.xml"
minify_html = false # This breaks mermaid diagrams :(
ignored_content = ["content/@/blog/*.md"]
ignored_static = ["static/images/drawings/*/*.xcf"]

[markdown]
highlight_code = true
render_emoji = true
external_links_target_blank = true

[link_checker]
skip_prefixes = []
skip_anchor_prefixes = []
internal_level = "error"
external_level = "error"

[extra]
# Website
domain_name = "ewpratten.com"
# Me
name = "Evan Pratten"
profession = "Software Developer"
profile_photo = "/images/pfp/2022/460x460.webp"
# Accounts
email = "evan@ewpratten.com"
github = "ewpratten"
linkedin = "ewpratten"
# Announcements
# home_announcement = "Test content"
# global_announcement = "Global announcement content test"
