services:
  jekyll:
    build:
      context: .
      dockerfile: Dockerfile
    command: serve --watch
    platform: linux/x86_64
    stdin_open: true
    tty: true
    volumes:
      - .:/srv/jekyll:Z
      - ./Gemfile:/srv/jekyll/Gemfile
    ports:
      - "127.0.0.1:4000:4000"