name: Deploy website
on:
  push:
    # branches:
    #   - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Call the Docker Compose stack to build the page
        run: docker-compose exec jekyll build
