name: Deploy ewpratten.com

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout master
        uses: actions/checkout@v4

      # - name: Build builder image
      #   run: docker compose build

      # - name: Build website
      #   run: docker compose run jekyll build

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
        
      - name: Install Jekyll
        run: gem install jekyll bundler

      - name: Install dependencies
        run: bundle install

      - name: Build website
        run: bundle exec jekyll build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ewpratten
          directory: _site
          wranglerVersion: '2'
