name: Build Commit
on:
  push:
    branches:
      - "*"
      - "!master"

jobs:
  call-build:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: ./.github/workflows/build-site.yml
