name: Build Website

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm install

      - name: Compile assets
        run: make

      - name: Build
        uses: TonySpegel/zola-build-action@v1
        env:
          CONFIG_FILE: "config.toml"

      - name: Disable Jekyll
        run: sudo touch ./public/.nojekyll

      - name: Delete dist gitignore
        run: sudo rm -f ./public/dist/.gitignore
