name: Build Website

on:
  push:
    branches:
      - "*"
      # Master has its own set of build rules,
      # and will eventually call this script on its own
      - "!master"
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Setup Node.js
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: 12.x

      # - name: Install dependencies
      #   run: npm install

      - name: Allow all dirs
        run: git config --global --add safe.directory '*'

      - name: Build only 
        uses: shalzz/zola-deploy-action@v0.16.1-1
        env:
          BUILD_ONLY: true

      - name: Disable Jekyll
        run: sudo touch ./public/.nojekyll

      - name: Delete dist gitignore
        run: sudo rm -f ./public/dist/.gitignore

      - name: Upload site as artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./public
