name: Copyright Check

on:
  push:

jobs:
  check-copyright:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch current year
        run: |
            YEAR=$(date +%Y)
            echo "Current year is $YEAR"
      - name: Update LICENSE file
        run: |
            echo "Copyright (c) 2017-${YEAR}, Evan Pratten, All rights reserved." > /tmp/correct_license
      - name: Check if LICENSE file has changed
        id: license-check
        run: |
            diff /tmp/correct_license ${GITHUB_WORKSPACE}/LICENSE