name: Copyright Check

on:
  push:

jobs:
  check-copyright-year:
    name: Check Copyright Year
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate expected LICENSE file
        run: |
            echo "Copyright (c) 2017-$(date +%Y), Evan Pratten, All rights reserved." > /tmp/correct_license
      - name: Check if LICENSE year is correct
        id: license-check
        run: |
            diff /tmp/correct_license ${GITHUB_WORKSPACE}/LICENSE