name: Copyright Check

on:
  schedule:
    - cron: "0 0 1 1 *"
  push:

jobs:
  check-copyright:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch current year
        run: |
            YEAR=$(date +%Y)
            echo "Current year is $YEAR"
      - name: Update LICENSE file
        run: |
            echo "Copyright (c) ${YEAR}, Evan Pratten, All rights reserved." > /tmp/correct_license
      - name: Check if LICENSE file has changed
        run: |
            diff /tmp/correct_license LICENSE
            if [ $? -eq 0 ]; then
                echo "LICENSE file is up to date"
            else
                echo "LICENSE file is out of date"
                exit 1
            fi