name: Build & Deploy Site

on:
  push:

jobs:
  build_dev:
    name: Development Build
    if: github.ref != 'refs/heads/master'
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout master
        uses: actions/checkout@v4

      - name: Build only 
        uses: shalzz/zola-deploy-action@v0.18.0
        env:
          BUILD_ONLY: true
          BUILD_FLAGS: --drafts

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ewpratten
          directory: public
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: '2'

  build_prod:
    name: Production Build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout master
        uses: actions/checkout@v4

      - name: Build only 
        uses: shalzz/zola-deploy-action@v0.18.0
        env:
          BUILD_ONLY: true

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ewpratten
          directory: public
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: '2'