name: Deploy
on:
  push:
    branches:
      - "master"

jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

      # - name: Download bundle artifact
      #   uses: actions/download-artifact@v2
      #   with:
      #     name: website-static-bundle
      #     path: ./public

      # - name: Deploy to GitHub Pages
      #   if: success()
      #   uses: crazy-max/ghaction-github-pages@v2
      #   with:
      #     target_branch: gh-pages
      #     build_dir: public
      #     fqdn: ewpratten.com
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
