name: Deploy ewp.fyi

on:
  push:
    branches:
      - master
    paths:
      - 'sites/ewp.fyi/**'

jobs:

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout master
        uses: actions/checkout@v4

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ewp-fyi
          directory: sites/ewp.fyi
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: '2'
