name: ewpratten.com

on:
  push:
    paths:
      - ".github/workflows/ewpratten-com.yml"
      - "sites/ewpratten.com/**"

env:
  ZOLA_VERSION: 0.15.3

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment: production
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Download Zola
        run: |
          wget https://github.com/getzola/zola/releases/download/v$ZOLA_VERSION/zola-v$ZOLA_VERSION-x86_64-unknown-linux-gnu.tar.gz -O /tmp/zola.tar.gz
          tar -xvf /tmp/zola.tar.gz -C /tmp
      - name: Build
        run: |
          cd sites/ewpratten.com
          /tmp/zola build
      - name: Deploy
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: "ewpratten"
          workingDirectory: "sites/ewpratten.com"
          directory: "public"
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

