name: ewpratten.com

on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Download Zola
        run: |
          wget https://github.com/getzola/zola/releases/download/v0.17.2/zola-v0.17.2-x86_64-unknown-linux-gnu.tar.gz -O /tmp/zola.tar.gz
          tar -xvf /tmp/zola.tar.gz -C /tmp
      - name: Build
        run: |
          cd sites/ewpratten.com
          /tmp/zola build 
