name: Deploy retrylife.ca

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/retrylife-ca.yml'
      - 'sites/retrylife.ca/**'

jobs:

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout master
        uses: actions/checkout@v4

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: retrylife-ca
          directory: sites/retrylife.ca
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: '2'
